oursweetspace/urls.py
"""定义URL模式"""

from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'oursweetspace'
urlpatterns = [
    #主页
    path('', views.index, name= 'index'),
    
    #漂流瓶

    # 显示已功能介绍、以及拾起的对方的漂流瓶概览
    path('drift_bottles/', views.bottles, name= 'bottles'),
    # 显示某个漂流瓶的细节内容
    path('drift_bottles/<int:bottle_id>',views.bottle, name= 'bottle'),
    # 用于新建漂流瓶
    path('new_bottle/',views.new_bottle, name= 'new_bottle'),
    
    #心愿单

    # 显示所有主题
    path('lists/', views.topics, name='topics'),
    # 某一主题的详细页面内容
    path('lists/<int:topic_id>/', views.topic, name='topic'),
    # 用于添加新主题的页面
    path('new_topic/', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # 用于编辑entry的页面
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # 用于删除entry
    path('delete_entry/<int:entry_id>/', views.delete_entry, name="delete_entry"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sweet_space/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oursweetspace.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
"""为应用users定义url模式"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# 包含django默认身份验证url
	path('', include('django.contrib.auth.urls')),
	# 用户注册
	path('register/', views.register, name= 'register'),
	# 登录
	path('login/', views.login_view, name= 'login'),
	# 注销
	path('logout/', views.logout_view, name= 'logout'),
	# 注销成功 回到首页
	path('logged_out/', views.logged_out, name='logged_out'),
]

oursweetspace/models.py
from django.conf import settings
from django.db import models

class Bottletext(models.Model):
    """漂流瓶内容及相关信息"""
    title = models.TextField(max_length=100, default = '默认标题')
    text = models.TextField(max_length=2000)
    image = models.ImageField(upload_to='images/', max_length=100000000)
    date_added = models.DateTimeField(auto_now_add=True)
    date_unlock = models.DateTimeField()
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_bottletexts', null=True, blank=True)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_bottletexts', null=True, blank=True)


    def __str__(self):
        """返回文本字段"""
        return self.text


#心愿单模型
class Topic(models.Model):
    """心愿单的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='created_topic', null=True, blank=True)

    def __str__(self):
        """返回字符串表示"""
        return self.text


class Entry(models.Model):
    """Something specific in a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
 
    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

oursweetspace/forms.py
from django import forms

from .models import Bottletext, Topic, Entry

class BottleForm(forms.ModelForm):
    class Meta:
        model = Bottletext
        fields = ['title', 'text', 'image', 'date_unlock']
        widgets = {
            'date_unlock': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }

    def __init__(self, *args, **kwargs):
        super(BottleForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

#心愿单
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry：'}
        widgets = {'text': forms.Textarea(attrs={'cols': 200})}

oursweetspace/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Bottletext, Topic, Entry
from .forms import BottleForm, TopicForm, EntryForm

from django.utils import timezone

# Create your views here.
def index(request):
    """整个空间的主页"""
    return render(request, 'oursweetspace/index.html')


#漂流瓶
@login_required
def bottles(request):
    """显示所有已捡到且已解锁的瓶子标题"""
    now = timezone.now()
    bottles = Bottletext.objects.filter(receiver=request.user, date_unlock__lt=now).order_by('-date_added')
    context = {'bottles': bottles}
    return render(request, 'oursweetspace/bottles.html', context)


@login_required
def bottle(request, bottle_id):
    """显示瓶子内的详细信息"""
    bottle = Bottletext.objects.get(id= bottle_id)
    if bottle.receiver != request.user:
        raise Http404

    context = {'bottle': bottle}
    return render(request,'oursweetspace/bottle.html', context)


@login_required
def new_bottle(request):
    """新建漂流瓶"""
    if request.method != 'POST':
        form = BottleForm()
    else:
        #process data
        form = BottleForm(request.POST, request.FILES)
        if form.is_valid():
            new_bottle = form.save(commit= False)
            new_bottle.creator = request.user  #表单里继承了模型全部信息，在表单实现，填入模型的信息！
            if new_bottle.creator.user_lover:
                lover = new_bottle.creator.user_lover
                new_bottle.receiver = lover
            new_bottle.save()
            return redirect('oursweetspace:index')

    #显示空表单或无效
    context = {'form': form}
    return render(request,'oursweetspace/new_bottle.html', context)



#心愿单
@login_required
def topics(request):
    """显示当前用户及其配对用户的所有主题"""
    user_topics = Topic.objects.filter(owner=request.user)
    if request.user.user_lover:
        lover = request.user.user_lover
        lover_topics = Topic.objects.filter(owner=lover)
        user_topics |= lover_topics  # 使用 | 运算符合并两个查询集

    topics = user_topics.order_by("date_added")
    context = {'usertopics': topics}
    return render(request, 'oursweetspace/topics.html', context)



@login_required
def topic(request, topic_id):
    """显示某一主题，及内部所有条目"""
    topic = Topic.objects.get(id= topic_id)
    # 确认该topic属于该用户或其lover
    if topic.owner != request.user and topic.owner !=request.user.user_lover:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'usertopic': topic, 'userentries': entries}
    return render(request, 'oursweetspace/topic.html', context) 


@login_required
def new_topic(request):
    """用户添加新主题"""
    if request.method != 'POST':
        #未提交数据：创建新表单
        form = TopicForm()
    else:
        #POST提交的数据：对数据进行处理
        form = TopicForm(data= request.POST)
        if form.is_valid():
            new_topic = form.save(commit= False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('oursweetspace:topics')

    #显示空表单/指出数据无效
    context = {'form': form}
    return render(request,'oursweetspace/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定主题中添加条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user and topic.owner !=request.user.user_lover:
        raise Http404

    if request.method != 'POST':
        #no data    
        form = EntryForm()
    else:
        #data processing
        form = EntryForm(data= request.POST)
        if form.is_valid():
            new_entry = form.save(commit= False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('oursweetspace:topic',topic_id = topic_id)

    #显示空表单或指出表单数据无效
    context = {'topic': topic, 'form': form}
    return render(request,'oursweetspace/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user and topic.owner !=request.user.user_lover:
        raise Http404

    if request.method != 'POST':
        #初次请求：使用当前条目？？？
        form = EntryForm(instance= entry)
    else:
        #process POST提交的数据  
        form = EntryForm(instance= entry, data= request.POST)
        if form.is_valid():
            form.save()
            return redirect('oursweetspace:topic', topic_id= topic.id)#没关系 后面的topic是类

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'oursweetspace/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user and topic.owner !=request.user.user_lover:
        raise Http404
    
    # 确保请求方法是POST，以避免非法请求
    if request.method == 'POST':
        entry.delete()
        return redirect('oursweetspace:topic', topic_id = topic.id)  # 重定向到一个视图，例如条目列表
    else:
        # 如果不是POST请求，可以重定向或显示一个错误页面
        return redirect('oursweetspace:topic')

oursweetspace/templates/oursweetspace/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Our Sweetspace</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'oursweetspace:index'%}">
        Sweet Space</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'oursweetspace:bottles'%}">
              漂流瓶</a></li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'oursweetspace:topics'%}">
              To-do-lists</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <button class="nav-link" onclick="logout()">Log out</button>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

  <!-- JavaScript -->
  <script>
    function logout() {
      var form = document.createElement('form');
      form.method = 'POST';
      form.action = '{% url "users:logout" %}';
      var csrf_token = document.createElement('input');
      csrf_token.type = 'hidden';
      csrf_token.name = 'csrfmiddlewaretoken';
      csrf_token.value = '{{ csrf_token }}';
      form.appendChild(csrf_token);
      document.body.appendChild(form);
      form.submit();
    }
  </script>
</body>

</html>

oursweetspace/templates/oursweetspace/bottle.html
{% extends 'oursweetspace/base.html' %}

{% load static %}

{% block page_header %}
<head>
    <meta charset="UTF-8">
    <title>{{ bottle.title }}</title>

</head>
<body>
    <div class="container">
        <h1>{{ bottle.title }}</h1>
        <p>{{ bottle.text | linebreaksbr }}</p>
        {% if bottle.image %}
            <img src="{{ bottle.image.url }}" alt="{{ bottle.title }}">
        {% else %}
            <p> </p>
        {% endif %}
        <p>创建时间: {{ bottle.date_added }}</p>
        {% if bottle.date_unlock %}
            <p>解锁时间: {{ bottle.date_unlock }}</p>
        {% endif %}
    </div>
</body>

{% endblock  %}

oursweetspace/templates/oursweetspace/bottles.html
{% extends 'oursweetspace/base.html' %}

{% block content %}
<h2>已拾起的漂流瓶</h2>

<p>小小漂流瓶，载着爱，顺着时空的河流缓缓前进，缓缓漂流，直到很久···很久后的某一天，悄悄抵达ta心灵的彼岸······
</p>

<ul>
    {% for bottle in bottles %}
    <p>暂时还没有新的漂流瓶飘过来哦，ta一定想把藏在心底的话，告诉很久很久之后的你，耐心等等吧！</p>
    <li>
        <a href="{% url 'oursweetspace:bottle' bottle_id=bottle.id %}">{{ bottle.title }}</a>
        <p>这个漂流瓶漂呀漂，终于在{{ bottle.date_unlock }}抵达了你的岸边！</p>
        <!-- 其他你想显示的字段 -->
    </li>
    {% empty %}
    <li>呜呜！还没有漂流瓶飘过来哦，ta一定想把要说的话，告诉很久很久之后的你，耐心等等吧！</li>
    {% endfor %}
</ul>

<a href="{% url 'oursweetspace:new_bottle' %}">扔出一个漂流瓶，写下对心爱的ta想说的话！</a>
<p>    可以设置 漂流的最短时限/预期到达时间，之后随机的某一天，ta就会收到你的留言啦！</p>
{% endblock %}

oursweetspace/templates/oursweetspace/edit_entry.html
{% extends "oursweetspace/base.html" %}

{% block content %}

  <p>
  	<a href="{% url 'oursweetspace:topic' topic_id=topic.id %}">{{topic}}</a>
  </p>

  <p>Edit entry:</p>

  <form action="{% url 'oursweetspace:edit_entry' entry_id=entry.id %}" method="post">
  	{% csrf_token %}
    {{form.as_p}}
    <button name='submit'>Save changes</button>
  </form>


  <form action="{% url 'oursweetspace:delete_entry' entry.id %}" method="post">
    {% csrf_token %}
    <button type="submit">永久删除这一条目！</button>
  </form>


{% endblock content %}

oursweetspace/templates/oursweetspace/index.html
{% extends "oursweetspace/base.html" %}

{% block content %}
<p>情侣空间</p>
{% endblock %}

oursweetspace/templates/oursweetspace/new_bottle.html
{% extends 'oursweetspace/base.html' %}

{% block content %}
  <p>制作一个漂流瓶！</p>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_title">标题：</label>
    {{ form.title }}
    <label for="id_text">正文:</label>
    {{ form.text }}
    <label for="id_image">上传图片（可选）:</label>
    {{ form.image }}
    <label for="id_date_unlock">解锁日期:</label>
    {{ form.date_unlock }}
    <button type="submit">扔进大海！</button>
  </form>


  <p>宝宝注意哦！！！漂流瓶一旦扔出，会越飘越远，再也不能修改了哦！</p>

{% endblock content %}

oursweetspace/templates/oursweetspace/new_entry.html
{% extends "oursweetspace/base.html" %}

{% block content %}

  <p><a href="{% url 'oursweetspace:topic' topic.id %}">{{topic}}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'oursweetspace:new_entry' topic.id %}" method="post">
  	{% csrf_token %}
  	{{form.as_p}}
  	<button name="submit">Add entry</button>
  </form>

{% endblock content %}

oursweetspace/templates/oursweetspace/new_topic.html
{% extends "oursweetspace/base.html" %}

{% block content %}
  <p>Add a new topic:</p>
    
  <form action="{% url 'oursweetspace:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>
  </form>
    
{% endblock content %}

oursweetspace/templates/oursweetspace/topic.html
{% extends 'oursweetspace/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'oursweetspace:new_entry' usertopic.id %}">Add new entry</a>
  </p>

  <ul>
  {% for entry in userentries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'oursweetspace:edit_entry' entry.id %}">
            edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

oursweetspace/templates/oursweetspace/topics.html
{% extends "oursweetspace/base.html" %}

{% block page_header %}
  <h1>心愿清单</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in usertopics %}
      <li><h3>
        <a href="{% url 'oursweetspace:topic' topic_id=topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'oursweetspace:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}